nombre = str(input("ingrese su nombre: "))
apellido = str(input("ingrese su apellido: "))
cod_seccion = str(input("ingrese el codigo se su secccion: "))
sede = str(input("ingrese su sede: "))

print("------------------------------------------------")
print("bienvenido ",nombre, apellido)
print("su seccion es: ",cod_seccion)
print("en la sede de: ",sede)
print("------------------------------------------------")